config/routes.rb
Rails.application.routes.draw do
  #get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "users#index"

  

  resources :users
  #need to create, edit, destroy

  get '/users/new', to: 'users#new', as: 'activate'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  
  
  
  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
    
  end

  def new
    @user = User.new
    #creates but does not save


  end


  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end


    def destroy
      @user = User.find(params[:id])
      @user.destroy
  
      redirect_to root_path
    end
  

  end




  private
    def user_params
      params.require(:user).permit(:name, :job)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :job %><br>
    <%= form.text_area :job %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<p> Index of users <p>

<div>
  <% @users.each do |user| %>
    <div><%= user.name.to_s + " " + user.job.to_s %></div>
  <% end %>
</div>

<p>Create a new user: </p>
<p><%= link_to "New User", activate_path(@user) %> </p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :job %><br>
    <%= form.text_area :job %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>hey its me your user</h1>

<%= 'Name: ' + @user.name.to_s %> </br>
<%= 'Occupation: ' + @user.job.to_s %>

<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>
  <li><%= link_to "Destroy", user_path(@user),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>